# Generated by Django 5.1 on 2024-08-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_dish_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, default='dishes/placeholder.jpg', null=True, upload_to='dishes/'),
        ),
    ]
